name = "shiny-feather-4c46"
main = "src/index.ts"
compatibility_date = "2024-07-12"

[vars]
DATABASE_URL = "postgresql://neondb_owner:npg_PdK64IhfwNMa@ep-winter-forest-a2lyuvnc-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
